# Generated by Django 4.2.6 on 2023-10-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmain', '0002_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='radius',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Радиус поиска ТС'),
        ),
    ]
