# Generated by Django 4.2.6 on 2023-10-23 14:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tmain.models


class Migration(migrations.Migration):

    dependencies = [
        ('tmain', '0003_alter_user_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rented', models.BooleanField(default=False, verbose_name='Арендовано ли ТС?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступно ли ТС для аренды?')),
                ('transport_type', models.CharField(choices=[('c', 'Машина'), ('m', 'Мотоцикл'), ('s', 'Самокат')], max_length=1)),
                ('model', models.CharField(max_length=100, verbose_name='Модель ТС')),
                ('color', models.CharField(max_length=80, verbose_name='Цвет ТС')),
                ('identifier', models.CharField(validators=[tmain.models.validate_identifier], verbose_name='Идентификатор ТС')),
                ('description', models.CharField(help_text='Максимальная длина описания                                               - 500 символов', max_length=500, verbose_name='Описание ТС')),
                ('latitude', models.IntegerField(help_text='Координаты ТС по широте', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Широта')),
                ('longitude', models.IntegerField(help_text='Координаты ТС по долготе', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Долгота')),
                ('minute_price', models.FloatField(validators=[tmain.models.validate_gt_zero], verbose_name='Цена аренды за минуту')),
                ('day_price', models.FloatField(validators=[tmain.models.validate_gt_zero], verbose_name='Цена аренды за 1 сутки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец ТС')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала аренды')),
                ('time_end', models.DateTimeField(null=True, verbose_name='Дата конца аренды')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна ли аренда?')),
                ('price', models.FloatField(null=True, validators=[tmain.models.validate_gt_zero], verbose_name='Цена аренды')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmain.transport', verbose_name='ТС')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
            ],
        ),
    ]
