# Generated by Django 4.2.6 on 2023-10-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmain', '0004_transport_rent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспортные средства'},
        ),
    ]
