# Generated by Django 4.2.6 on 2023-10-23 18:34

from django.db import migrations, models
import tmain.models


class Migration(migrations.Migration):

    dependencies = [
        ('tmain', '0005_alter_rent_options_alter_transport_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='minute_price',
        ),
        migrations.AddField(
            model_name='transport',
            name='hour_price',
            field=models.FloatField(default=400, validators=[tmain.models.validate_gt_zero], verbose_name='Цена аренды за час'),
            preserve_default=False,
        ),
    ]
