# Generated by Django 4.2.6 on 2023-10-28 06:40

from django.db import migrations, models
import tmain.models


class Migration(migrations.Migration):

    dependencies = [
        ('tmain', '0006_remove_transport_minute_price_transport_hour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[tmain.models.validate_gt_zero], verbose_name='Цена аренды'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца аренды'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='identifier',
            field=models.CharField(unique=True, validators=[tmain.models.validate_identifier], verbose_name='Идентификатор ТС'),
        ),
    ]
